# Generated by Django 5.2.15 on 2026-06-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_tag_color_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['priority', 'name']},
        ),
    ]
